/**
 * Provider Generator
 *
 * Generates the BlendProvider wrapper component that consumers
 * put in their app. This file is safe to edit — the CLI won't
 * overwrite it once created.
 */

export function generateProviderCode(isNextJs: boolean): string {
    const useClientDirective = isNextJs ? "'use client'\n\n" : ''

    return `${useClientDirective}/**
 * BlendProvider — wraps your app with the Blend Design System theme.
 *
 * Generated by Blend Token Studio. Safe to edit.
 * Docs: https://blend.juspay.design/docs/getting-started
 */

import { ThemeProvider, Theme } from '@juspay/blend-design-system'
import '@juspay/blend-design-system/style.css'
import { componentTokens, darkComponentTokens } from './tokens'

type BlendProviderProps = {
    children: React.ReactNode
    theme?: 'light' | 'dark'
}

export function BlendProvider({ children, theme = 'light' }: BlendProviderProps) {
    const tokens = theme === 'dark' ? darkComponentTokens : componentTokens

    return (
        <ThemeProvider theme={theme as Theme} componentTokens={tokens}>
            {children}
        </ThemeProvider>
    )
}
`
}
