/**
 * Tokens Generator
 *
 * Generates the tokens.ts file that contains pre-resolved
 * component tokens for a brand config.
 *
 * This file is auto-generated and should NOT be edited manually.
 * Re-run `blend-token-studio brand` or `blend-token-studio pull` to update.
 */

import type { BrandConfig } from '@blend-design/token-engine'

/**
 * Generate the tokens.ts file content.
 *
 * For the default (no-brand) case, exports empty objects so ThemeProvider
 * falls back to Blend defaults.
 */
export function generateDefaultTokensCode(): string {
    return `/**
 * Blend Design System — Component Tokens
 *
 * Auto-generated by Blend Token Studio.
 * DO NOT EDIT — run \`npx blend-token-studio brand\` to customize.
 *
 * Brand: Blend Default
 */

import type { ComponentTokenType } from '@juspay/blend-design-system'

/** Light theme tokens (empty = Blend defaults) */
export const componentTokens: ComponentTokenType = {}

/** Dark theme tokens (empty = Blend defaults) */
export const darkComponentTokens: ComponentTokenType = {}
`
}

/**
 * Generate the tokens.ts file with pre-resolved brand tokens.
 *
 * The resolved tokens are serialized as a JSON literal embedded
 * in the TypeScript file. This means no runtime resolution cost —
 * tokens are statically available at import time.
 *
 * Note: Generated files use @ts-nocheck because JSON serialization loses
 * enum type information. Runtime behavior is correct; TypeScript types
 * are satisfied structurally even if not nominally.
 */
export function generateBrandTokensCode(
    brandConfig: BrandConfig,
    lightTokens: Record<string, unknown>,
    darkTokens: Record<string, unknown>
): string {
    const timestamp = new Date().toISOString()
    const lightJson = JSON.stringify(lightTokens, null, 4)
    const darkJson = JSON.stringify(darkTokens, null, 4)

    return `// @ts-nocheck
// Auto-generated by Blend Token Studio. DO NOT EDIT.
// Generated: ${timestamp}

import type { ComponentTokenType } from '@juspay/blend-design-system'

/** Light theme tokens for ${brandConfig.name} */
export const componentTokens: ComponentTokenType = ${lightJson} as ComponentTokenType

/** Dark theme tokens for ${brandConfig.name} */
export const darkComponentTokens: ComponentTokenType = ${darkJson} as ComponentTokenType
`
}
