export const DEMOS = [
    { id: 'buttons', label: 'Button' },
    { id: 'buttonV2', label: 'Button V2' },
    { id: 'buttonGroups', label: 'Button Group' },
    { id: 'buttonGroupV2', label: 'Button Group V2' },
    { id: 'tags', label: 'Tag' },
    { id: 'tagV2', label: 'Tag V2' },
    { id: 'tagGroupV2', label: 'Tag Group V2' },
    { id: 'badge', label: 'Badge' },
    { id: 'avatars', label: 'Avatar' },
    { id: 'avatarV2', label: 'Avatar V2' },
    { id: 'avatarGroup', label: 'Avatar Group' },
    { id: 'breadcrumb', label: 'Breadcrumb' },
    { id: 'breadcrumbV2', label: 'Breadcrumb V2' },
    { id: 'virtualList', label: 'Virtual List' },
    { id: 'upload', label: 'File Upload' },
    { id: 'input', label: 'Text Input' },
    { id: 'textInputV2', label: 'Text Input V2' },
    { id: 'textInputGroup', label: 'Text Input Group' },
    { id: 'textInputAutofillTest', label: 'Text Input Autofill Test' },
    { id: 'textInputAutofillTestV2', label: 'Text Input Autofill Test V2' },
    { id: 'searchInput', label: 'Search Input' },
    { id: 'searchInputV2', label: 'Search Input V2' },
    { id: 'otpInput', label: 'OTP Input' },
    { id: 'otpInputV2', label: 'OTP Input V2' },
    { id: 'unitInput', label: 'Unit Input' },
    { id: 'numberInput', label: 'Number Input' },
    { id: 'numberInputV2', label: 'Number Input V2' },
    { id: 'dropdownInput', label: 'Dropdown Input' },
    { id: 'textArea', label: 'Text Area' },
    { id: 'textAreaV2', label: 'Text Area V2' },
    { id: 'chatInput', label: 'Chat Input' },
    { id: 'chatInputV2', label: 'Chat Input V2' },
    { id: 'multiValueInput', label: 'Multi Value Input' },
    { id: 'multiValueInputV2', label: 'Multi Value Input V2' },
    { id: 'keyValuePair', label: 'Key Value Pair' },
    { id: 'keyValuePairV2', label: 'Key Value Pair V2' },
    { id: 'topbar', label: 'Topbar' },
    { id: 'menu', label: 'Menu' },
    { id: 'menuV2', label: 'Menu V2' },
    { id: 'singleSelect', label: 'Single Select' },
    { id: 'singleSelectV2', label: 'Single Select V2' },
    { id: 'singleSelectGroup', label: 'Single Select Group' },
    { id: 'multiSelect', label: 'Multi Select' },
    { id: 'multiSelectV2', label: 'Multi Select V2' },
    { id: 'multiSelectGroup', label: 'Multi Select Group' },
    { id: 'tabs', label: 'Tabs' },
    { id: 'tabsV2', label: 'Tabs V2' },
    { id: 'accordion', label: 'Accordion' },
    { id: 'accordionV2', label: 'Accordion V2' },
    { id: 'stepper', label: 'Stepper' },
    { id: 'stepperV2', label: 'Stepper V2' },
    { id: 'alerts', label: 'Alert' },
    { id: 'alertV2', label: 'Alert V2' },
    { id: 'snackbar', label: 'Snackbar' },
    { id: 'snackbarV2', label: 'Snackbar V2' },
    { id: 'tooltips', label: 'Tooltip' },
    { id: 'tooltipV2', label: 'Tooltip V2' },
    { id: 'modal', label: 'Modal' },
    { id: 'popover', label: 'Popover' },
    { id: 'popoverV2', label: 'Popover V2' },
    { id: 'drawer', label: 'Drawer' },
    { id: 'drawerV2', label: 'Drawer V2' },
    { id: 'charts', label: 'Charts' },
    { id: 'blendChart', label: 'Blend Chart' },
    { id: 'chartV2', label: 'Chart V2' },
    { id: 'outageCharts', label: 'Outage Charts' },
    { id: 'outageChartV2', label: 'Outage Charts V2' },
    { id: 'statCard', label: 'Stat Card' },
    { id: 'statCardV2', label: 'Stat Card V2' },
    { id: 'skeleton', label: 'Skeleton' },
    { id: 'card', label: 'Card' },
    { id: 'cardV2', label: 'Card V2' },
    { id: 'progressBar', label: 'Progress Bar' },
    { id: 'progressBarV2', label: 'Progress Bar V2' },
    { id: 'dataTable', label: 'Data Table' },
    { id: 'dataRangePicker', label: 'Date Picker' },
    { id: 'codeBlock', label: 'Code Block' },
    { id: 'codeEditor', label: 'Code Editor' },
    { id: 'codeEditorV2', label: 'Code Editor V2' },
    { id: 'timeline', label: 'Timeline' },
    { id: 'formElements', label: 'Form Elements' },
    { id: 'radio', label: 'Radio' },
    { id: 'radioV2', label: 'Radio V2' },
    { id: 'checkbox', label: 'Checkbox' },
    { id: 'checkboxV2', label: 'Checkbox V2' },
    { id: 'switch', label: 'Switch' },
    { id: 'switchV2', label: 'Switch V2' },
    { id: 'allComponents', label: 'All Components' },
    { id: 'themeProvider', label: 'Theme Provider' },
    { id: 'accessibility', label: 'Accessibility Dashboard' },
] as const

export type DemoId = (typeof DEMOS)[number]['id']
