import { useMemo, useState } from 'react'
import {
    AlertV2,
    AlertV2Type,
    ButtonV2,
    ButtonV2Type,
    DrawerV2,
    DrawerV2Content,
    DrawerV2Overlay,
    DrawerV2Portal,
    DrawerV2Trigger,
    TextInputV2,
} from '@juspay/blend-design-system'

// Generated by `blend-token-studio init` + `brand` (or commit your own).
import { BlendProvider } from './blend/provider'

export default function App() {
    const [theme, setTheme] = useState<'light' | 'dark'>('light')
    const [name, setName] = useState('')
    const [drawerOpen, setDrawerOpen] = useState(false)

    const bg = useMemo(
        () => (theme === 'dark' ? '#0b1220' : '#f6f7fb'),
        [theme]
    )

    return (
        <BlendProvider theme={theme}>
            <div
                style={{
                    minHeight: '100vh',
                    padding: 24,
                    background: bg,
                }}
            >
                <div style={{ maxWidth: 960, margin: '0 auto' }}>
                    <div
                        style={{
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'space-between',
                            gap: 12,
                            marginBottom: 16,
                        }}
                    >
                        <div>
                            <div style={{ fontSize: 18, fontWeight: 700 }}>
                                Tokenizer Sandbox
                            </div>
                            <div style={{ opacity: 0.7, fontSize: 13 }}>
                                Run `pnpm token:brand` and see styles update.
                            </div>
                        </div>

                        <ButtonV2
                            buttonType={ButtonV2Type.SECONDARY}
                            text={`Theme: ${theme}`}
                            onClick={() =>
                                setTheme((t) =>
                                    t === 'light' ? 'dark' : 'light'
                                )
                            }
                        />
                    </div>

                    <AlertV2
                        type={AlertV2Type.NEUTRAL}
                        title="How to test"
                        description="From this folder: pnpm token:init, then pnpm token:brand, then pnpm dev."
                    />

                    <div style={{ height: 16 }} />

                    <div
                        style={{
                            display: 'grid',
                            gridTemplateColumns:
                                'repeat(auto-fit, minmax(280px, 1fr))',
                            gap: 16,
                        }}
                    >
                        <div
                            style={{
                                padding: 16,
                                borderRadius: 12,
                                background:
                                    theme === 'dark' ? '#0f1b33' : '#ffffff',
                                border:
                                    theme === 'dark'
                                        ? '1px solid rgba(255,255,255,0.08)'
                                        : '1px solid rgba(0,0,0,0.08)',
                            }}
                        >
                            <div style={{ fontWeight: 700, marginBottom: 8 }}>
                                Inputs
                            </div>
                            <TextInputV2
                                label="Name"
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                placeholder="Type here"
                            />
                        </div>

                        <div
                            style={{
                                padding: 16,
                                borderRadius: 12,
                                background:
                                    theme === 'dark' ? '#0f1b33' : '#ffffff',
                                border:
                                    theme === 'dark'
                                        ? '1px solid rgba(255,255,255,0.08)'
                                        : '1px solid rgba(0,0,0,0.08)',
                            }}
                        >
                            <div style={{ fontWeight: 700, marginBottom: 8 }}>
                                DrawerV2
                            </div>

                            <DrawerV2
                                open={drawerOpen}
                                onOpenChange={setDrawerOpen}
                            >
                                <DrawerV2Trigger asChild>
                                    <ButtonV2
                                        buttonType={ButtonV2Type.PRIMARY}
                                        text="Open Drawer"
                                    />
                                </DrawerV2Trigger>

                                <DrawerV2Portal>
                                    <DrawerV2Overlay />
                                    <DrawerV2Content>
                                        <div
                                            style={{
                                                padding: 16,
                                                display: 'grid',
                                                gap: 12,
                                            }}
                                        >
                                            <div
                                                style={{
                                                    fontSize: 16,
                                                    fontWeight: 700,
                                                }}
                                            >
                                                Hello {name || 'there'}
                                            </div>
                                            <div style={{ opacity: 0.75 }}>
                                                This is a quick end-to-end check
                                                that tokens + styles work.
                                            </div>
                                            <ButtonV2
                                                buttonType={
                                                    ButtonV2Type.SECONDARY
                                                }
                                                text="Close"
                                                onClick={() =>
                                                    setDrawerOpen(false)
                                                }
                                            />
                                        </div>
                                    </DrawerV2Content>
                                </DrawerV2Portal>
                            </DrawerV2>
                        </div>
                    </div>
                </div>
            </div>
        </BlendProvider>
    )
}
