/**
 * Blend Design System — Component Tokens
 *
 * Auto-generated by Blend Token Studio.
 * DO NOT EDIT — run `npx blend-token-studio brand` to customize.
 *
 * Brand: Blend Default
 */

import type { ComponentTokenType } from '@juspay/blend-design-system'

/** Light theme tokens (empty = Blend defaults) */
export const componentTokens: ComponentTokenType = {}

/** Dark theme tokens (empty = Blend defaults) */
export const darkComponentTokens: ComponentTokenType = {}
