import { patchResizeObserver } from './pollyfills/resizeObserverPollyfill'

patchResizeObserver()

// ---------------------------------------------------------------------------
// Core exports
// ---------------------------------------------------------------------------
export * from './context'
export * from './tokens'
export { FOUNDATION_THEME } from './tokens'
export type { FoundationTokenType } from './tokens/theme.token'
export { Theme } from './context'

// ---------------------------------------------------------------------------
// Components without a V2 replacement
// ---------------------------------------------------------------------------
export * from './components/AvatarGroup'
export * from './components/Badge'
export * from './components/CodeBlock'
export * from './components/DataTable'
export * from './components/DateRangePicker'
export * from './components/SingleDatePicker'
export * from './components/TimePicker'
export * from './components/Directory'
export * from './components/Inputs/DropdownInput'
export * from './components/Inputs/UnitInput'
export * from './components/Skeleton'
export * from './components/Slider'
export * from './components/SplitTag'
export * from './components/VirtualList'

// ---------------------------------------------------------------------------
// Current component APIs
// ---------------------------------------------------------------------------
export * from './components/ButtonV2'
export { ButtonV2 as Button } from './components/ButtonV2'
export type { ButtonV2Props as ButtonProps } from './components/ButtonV2'
export * from './components/AlertV2'
export { AlertV2 as Alert } from './components/AlertV2'
export * from './components/TagV2'
export { TagV2 as Tag } from './components/TagV2'
export * from './components/SelectorV2/CheckboxV2'
export { CheckboxV2 as Checkbox } from './components/SelectorV2/CheckboxV2'
export * from './components/SelectorV2/RadioV2'
export { RadioV2 as Radio } from './components/SelectorV2/RadioV2'
export * from './components/SelectorV2/SwitchV2'
export { SwitchV2 as Switch } from './components/SelectorV2/SwitchV2'
export * from './components/BreadcrumbV2'
export { BreadcrumbV2 as Breadcrumb } from './components/BreadcrumbV2'
export * from './components/AvatarV2'
export { AvatarV2 as Avatar } from './components/AvatarV2'
export * from './components/TooltipV2'
export { TooltipV2 as Tooltip } from './components/TooltipV2'
export * from './components/ProgressBarV2'
export { ProgressBarV2 as ProgressBar } from './components/ProgressBarV2'
export * from './components/Spinner'
export * from './components/EmptyState'
export * from './components/StatCardV2'
export { StatCardV2 as StatCard } from './components/StatCardV2'
export * from './components/CardV2'
export { CardV2 as Card } from './components/CardV2'
export * from './components/AccordionV2'
export { AccordionV2 as Accordion } from './components/AccordionV2'
export * from './components/InputsV2/TextInputV2'
export { TextInputV2 as TextInput } from './components/InputsV2/TextInputV2'
export * from './components/InputsV2/TextAreaV2'
export { TextAreaV2 as TextArea } from './components/InputsV2/TextAreaV2'
export * from './components/DrawerV2'
export { DrawerV2 as Drawer } from './components/DrawerV2'
export * from './components/TabsV2'
export { TabsV2 as Tabs } from './components/TabsV2'
export * from './components/ChartsV2'
export { ChartV2 as Chart } from './components/ChartsV2'
export { ChartV2 as Charts } from './components/ChartsV2'
export * from './components/ButtonV2/ButtonGroupV2'
export { ButtonGroupV2 as ButtonGroup } from './components/ButtonV2/ButtonGroupV2'
export * from './components/common/TruncatedTextWithTooltipV2'
export * from './components/PopoverV2'
export { PopoverV2 as Popover } from './components/PopoverV2'
export * from './components/ModalV2'
export { ModalV2 as Modal } from './components/ModalV2'
export * from './components/SidebarV2'
export { SidebarV2 as Sidebar } from './components/SidebarV2'
export * from './components/StepperV2'
export { StepperV2 as Stepper } from './components/StepperV2'
export * from './components/TagGroupV2'
export * from './components/Timeline'
export * from './components/TopbarV2'
export { TopbarV2 as Topbar } from './components/TopbarV2'
export * from './components/SelectV2'
export * from './components/InputsV2/MultiValueInputV2'
export { MultiValueInputV2 as MultiValueInput } from './components/InputsV2/MultiValueInputV2'
export * from './components/InputsV2/NumberInputV2'
export { NumberInputV2 as NumberInput } from './components/InputsV2/NumberInputV2'
export * from './components/InputsV2/OTPInputV2'
export { OTPInputV2 as OTPInput } from './components/InputsV2/OTPInputV2'
export * from './components/InputsV2/SearchInputV2'
export { SearchInputV2 as SearchInput } from './components/InputsV2/SearchInputV2'
export { UploadV2 } from './components/InputsV2/UploadV2'
export { UploadV2 as Upload } from './components/InputsV2/UploadV2'
export {
    UploadState as UploadV2State,
    UploadDragState as UploadV2DragState,
    UploadErrorReason,
} from './components/InputsV2/UploadV2'
export type {
    UploadV2Props,
    UploadFileV2,
    UploadErrorReasonValue,
    UploadV2TokensType,
    ResponsiveUploadV2Tokens,
} from './components/InputsV2/UploadV2'
export * from './components/SnackbarV2'
export { SnackbarV2 as Snackbar } from './components/SnackbarV2'
export * from './components/CodeEditorV2'
export { CodeEditorV2 as CodeEditor } from './components/CodeEditorV2'
export * from './components/KeyValuePairV2'
export { KeyValuePairV2 as KeyValuePair } from './components/KeyValuePairV2'
export * from './components/MenuV2'
export { MenuV2 as Menu } from './components/MenuV2'
export * from './components/MultiSelectV2'
export { MultiSelectV2 as MultiSelect } from './components/MultiSelectV2'
export * from './components/SingleSelectV2'
export { SingleSelectV2 as SingleSelect } from './components/SingleSelectV2'
export * from './components/SelectListV2'
export * from './components/InputsV2/ChatInputV2'
export { ChatInputV2 as ChatInput } from './components/InputsV2/ChatInputV2'
