/**
 * Token Engine — re-exported from @blend-design/token-engine (workspace)
 *
 * Consumer import: import { resolveBrandTokens } from '@juspay/blend-design-system/tokens'
 *
 * This entry includes React component token resolvers.
 * For server-safe imports, use: '@juspay/blend-design-system/tokens/server'
 */

// @blend-design/token-engine is a workspace package (private, not published).
// Vite resolves it to source via alias, bundles it into this dist entry.

export {
    resolveBrandTokens,
    buildBrandFoundation,
    resolveAllTokens,
    V2_COMPONENT_KEYS,
    clearTokenCache,
    registerResolver,
    validateBrandConfig,
    diffBrandConfigs,
    generateColorScale,
    isValidHexColor,
    getContrastRatio,
    getContrastRatioHex,
    analyzeContrast,
    validatePaletteContrast,
    suggestForeground,
    hexToRgb,
    relativeLuminance,
    meetsWCAG,
    getPreset,
    listPresets,
    PRESETS,
    PRESET_BLEND_DEFAULT,
    PRESET_JUSPAY,
    PRESET_PURPLE,
    PRESET_GREEN,
    PRESET_ORANGE,
    resolveWithInheritance,
    validateAgainstLocks,
    extractOverridePaths,
    RADIUS_PRESETS,
    BRANCH_ID_PATTERN,
    VERSION_PATTERN,
    generateBranchId,
    parseBranchId,
    validateBranchId,
    validateVersion,
    incrementVersion,
    TEAM_ROLE_PERMISSIONS,
    BRANCH_COLLECTION,
    VERSION_SUBCOLLECTION,
    SNAPSHOT_SUBCOLLECTION,
    versionsPath,
    snapshotsPath,
    getDefaultPreferences,
    getDefaultOnboardingState,
    STORAGE_KEYS,
    canUserPerformAction,
} from '@blend-design/token-engine'

export type {
    BrandConfig,
    BrandColors,
    ColorOverrides,
    RadiusOverrides,
    ShadowOverrides,
    FontOverrides,
    ComponentOverrides,
    RadiusPreset,
    ValidationResult,
    ValidationError,
    ValidationWarning,
    TokenDiff,
    ContrastResult,
    ContrastViolation,
    WCAGLevel,
    WCAGContext,
    LockViolation,
    InheritanceResult,
    TokenLockEntry,
    BranchStatus,
    BranchVisibility,
    BranchPermissions,
    BranchOwner,
    BranchMeta,
    BranchReference,
    Branch,
    CreateBranchInput,
    UpdateBranchInput,
    Version,
    CreateVersionInput,
    Snapshot,
    CreateSnapshotInput,
    BranchListFilters,
    BranchListOptions,
    BranchListResult,
    BranchDiff,
    ResolvedTokensResponse,
    TeamRole,
    TeamPermissions,
    UserPreferences,
    OnboardingState,
} from '@blend-design/token-engine'
