export { default as useClickOutside } from './useClickOutside'
export { default as useScrollLock } from './useScrollLock'
export { default as usePreventParentScroll } from './usePreventParentScroll'
export { default as useDropdownInteractionLock } from './useDropdownInteractionLock'
export { createOutsideInteractionHandler } from './useDropdownInteractionLock'
export { default as useTruncationDetection } from './useTruncationDetection'
export type { UseTruncationDetectionOptions } from './useTruncationDetection'
