const buttonMeta = {
    componentName: 'Button',
    componentDescription:
        'An interactive button component with multiple variants, sizes, and states for user actions.',
    features: [
        'Multiple variants (primary, secondary, danger)',
        'Different sizes and states',
        'Icon support',
        'Loading states',
        'Accessibility features',
    ],
    usageExamples: [
        {
            title: 'Basic Button',
            description: 'Simple button usage',
            code: '<Button />',
        },
        {
            title: 'Button with Icon',
            description: 'Button with leading icon',
            code: '<Button text="Save" leadingIcon={<SaveIcon />} />',
        },
    ],
    props: [
        {
            propName: 'buttonType',
            propType: 'ButtonType',
            typeDefinition: `ButtonType`,
            propDescription: 'buttonType prop for Button',
            llmContext:
                'buttonType prop for Button - events property for Button',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'size',
            propType: 'ButtonSize',
            typeDefinition: `ButtonSize`,
            propDescription: 'size prop for Button',
            llmContext: 'size prop for Button - appearance property for Button',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'subType',
            propType: 'ButtonSubType',
            typeDefinition: `ButtonSubType`,
            propDescription: 'subType prop for Button',
            llmContext: 'subType prop for Button - general property for Button',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'text',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'text prop for Button',
            llmContext: 'text prop for Button - content property for Button',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'leadingIcon',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'leadingIcon prop for Button',
            llmContext:
                'leadingIcon prop for Button - events property for Button',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'trailingIcon',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'trailingIcon prop for Button',
            llmContext:
                'trailingIcon prop for Button - events property for Button',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'isLoading',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'isLoading prop for Button',
            llmContext: 'isLoading prop for Button - state property for Button',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'isDisabled',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'isDisabled prop for Button',
            llmContext:
                'isDisabled prop for Button - state property for Button',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'disabled',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'disabled prop for Button',
            llmContext: 'disabled prop for Button - state property for Button',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'onClick',
            propType: '() => void',
            typeDefinition: `() => void`,
            propDescription: 'onClick prop for Button',
            llmContext: 'onClick prop for Button - events property for Button',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'loading',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'loading prop for Button',
            llmContext: 'loading prop for Button - state property for Button',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'buttonGroupPosition',
            propType: "'center' | 'left' | 'right'",
            typeDefinition: `\'center\' | \'left\' | \'right\'`,
            propDescription: 'buttonGroupPosition prop for Button',
            llmContext:
                'buttonGroupPosition prop for Button - events property for Button',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'fullWidth',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'fullWidth prop for Button',
            llmContext:
                'fullWidth prop for Button - layout property for Button',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'justifyContent',
            propType: "CSSObject['justifyContent']",
            typeDefinition: `CSSObject[\'justifyContent\']`,
            propDescription: 'justifyContent prop for Button',
            llmContext:
                'justifyContent prop for Button - events property for Button',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
    ],
}

export default buttonMeta
