const chartsMeta = {
    componentName: 'Charts',
    componentDescription:
        'A comprehensive charting component supporting various chart types like line, bar, and pie charts.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
        'Part of the Blend design system',
    ],
    usageExamples: [
        {
            title: 'Basic Charts',
            description: 'Simple charts usage',
            code: '<Charts />',
        },
    ],
    props: [
        {
            propName: 'chartType',
            propType: 'ChartType',
            typeDefinition: `ChartType`,
            propDescription: 'chartType prop for Charts',
            llmContext:
                'chartType prop for Charts - general property for Charts',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'data',
            propType: 'NewNestedDataPoint[]',
            typeDefinition: `NewNestedDataPoint[]`,
            propDescription: 'data prop for Charts',
            llmContext: 'data prop for Charts - general property for Charts',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'xAxisLabel',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'xAxisLabel prop for Charts',
            llmContext:
                'xAxisLabel prop for Charts - content property for Charts',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'yAxisLabel',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'yAxisLabel prop for Charts',
            llmContext:
                'yAxisLabel prop for Charts - content property for Charts',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'colors',
            propType: 'string[]',
            typeDefinition: `string[]`,
            propDescription: 'colors prop for Charts',
            llmContext:
                'colors prop for Charts - appearance property for Charts',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'metrics',
            propType: 'string[]',
            typeDefinition: `string[]`,
            propDescription: 'metrics prop for Charts',
            llmContext: 'metrics prop for Charts - general property for Charts',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'slot1',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'slot1 prop for Charts',
            llmContext: 'slot1 prop for Charts - general property for Charts',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'slot2',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'slot2 prop for Charts',
            llmContext: 'slot2 prop for Charts - general property for Charts',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'slot3',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'slot3 prop for Charts',
            llmContext: 'slot3 prop for Charts - general property for Charts',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'legendPosition',
            propType: 'ChartLegendPosition',
            typeDefinition: `ChartLegendPosition`,
            propDescription: 'legendPosition prop for Charts',
            llmContext:
                'legendPosition prop for Charts - events property for Charts',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'chartHeaderSlot',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'chartHeaderSlot prop for Charts',
            llmContext:
                'chartHeaderSlot prop for Charts - general property for Charts',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'stackedLegends',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'stackedLegends prop for Charts',
            llmContext:
                'stackedLegends prop for Charts - general property for Charts',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'stackedLegendsData',
            propType: 'StackedLegendsDataPoint[]',
            typeDefinition: `StackedLegendsDataPoint[]`,
            propDescription: 'stackedLegendsData prop for Charts',
            llmContext:
                'stackedLegendsData prop for Charts - general property for Charts',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
    ],
}

export default chartsMeta
