const dropdowninputMeta = {
    componentName: 'DropdownInput',
    componentDescription:
        'A dropdowninput component for the Blend design system.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
    ],
    usageExamples: [
        {
            title: 'Basic DropdownInput',
            description: 'Simple dropdowninput usage',
            code: `<DropdownInput />`,
        },
    ],
    props: [
        {
            propName: 'label',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'label prop for DropdownInput',
            llmContext: 'label prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'sublabel',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'sublabel prop for DropdownInput',
            llmContext: 'sublabel prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'helpIconHintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'helpIconHintText prop for DropdownInput',
            llmContext: 'helpIconHintText prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'error',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'error prop for DropdownInput',
            llmContext: 'error prop for DropdownInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'errorMessage',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'errorMessage prop for DropdownInput',
            llmContext: 'errorMessage prop for DropdownInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'hintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'hintText prop for DropdownInput',
            llmContext: 'hintText prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'value',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'value prop for DropdownInput',
            llmContext: 'value prop for DropdownInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'onChange',
            propType: '(e: React.ChangeEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.ChangeEvent<HTMLInputElement>) => void`,
            propDescription: 'onChange prop for DropdownInput',
            llmContext: 'onChange prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'slot',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'slot prop for DropdownInput',
            llmContext: 'slot prop for DropdownInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'size',
            propType: 'TextInputSize',
            typeDefinition: `TextInputSize`,
            propDescription: 'size prop for DropdownInput',
            llmContext: 'size prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'dropDownValue',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'dropDownValue prop for DropdownInput',
            llmContext: 'dropDownValue prop for DropdownInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'onDropDownChange',
            propType: '(value: string) => void',
            typeDefinition: `(value: string) => void`,
            propDescription: 'onDropDownChange prop for DropdownInput',
            llmContext: 'onDropDownChange prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'dropDownItems',
            propType: 'SelectMenuGroupType[]',
            typeDefinition: `SelectMenuGroupType[]`,
            propDescription: 'dropDownItems prop for DropdownInput',
            llmContext: 'dropDownItems prop for DropdownInput',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'dropdownName',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'dropdownName prop for DropdownInput',
            llmContext: 'dropdownName prop for DropdownInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'onDropdownOpen',
            propType: '() => void',
            typeDefinition: `() => void`,
            propDescription: 'onDropdownOpen prop for DropdownInput',
            llmContext: 'onDropdownOpen prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onDropdownClose',
            propType: '() => void',
            typeDefinition: `() => void`,
            propDescription: 'onDropdownClose prop for DropdownInput',
            llmContext: 'onDropdownClose prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onBlur',
            propType: '(e: React.FocusEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLInputElement>) => void`,
            propDescription: 'onBlur prop for DropdownInput',
            llmContext: 'onBlur prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onFocus',
            propType: '(e: React.FocusEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLInputElement>) => void`,
            propDescription: 'onFocus prop for DropdownInput',
            llmContext: 'onFocus prop for DropdownInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
    ],
}

export default dropdowninputMeta
