const menuMeta = {
    componentName: 'Menu',
    componentDescription:
        'A navigation menu component with support for nested items and various layouts.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
        'Part of the Blend design system',
    ],
    usageExamples: [
        {
            title: 'Basic Menu',
            description: 'Simple menu usage',
            code: '<Menu />',
        },
    ],
    props: [
        {
            propName: 'trigger',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'trigger prop for Menu',
            llmContext: 'trigger prop for Menu - general property for Menu',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'items',
            propType: 'MenuV2GroupType[]',
            typeDefinition: `MenuV2GroupType[]`,
            propDescription: 'items prop for Menu',
            llmContext: 'items prop for Menu - general property for Menu',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'maxHeight',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'maxHeight prop for Menu',
            llmContext: 'maxHeight prop for Menu - layout property for Menu',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'minHeight',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'minHeight prop for Menu',
            llmContext: 'minHeight prop for Menu - layout property for Menu',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'maxWidth',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'maxWidth prop for Menu',
            llmContext: 'maxWidth prop for Menu - layout property for Menu',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'minWidth',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'minWidth prop for Menu',
            llmContext: 'minWidth prop for Menu - layout property for Menu',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'enableSearch',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'enableSearch prop for Menu',
            llmContext:
                'enableSearch prop for Menu - general property for Menu',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'searchPlaceholder',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'searchPlaceholder prop for Menu',
            llmContext:
                'searchPlaceholder prop for Menu - general property for Menu',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'open',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'open prop for Menu',
            llmContext: 'open prop for Menu - state property for Menu',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'onOpenChange',
            propType: '(open: boolean) => void',
            typeDefinition: `(open: boolean) => void`,
            propDescription: 'onOpenChange prop for Menu',
            llmContext: 'onOpenChange prop for Menu - events property for Menu',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'asModal',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'asModal prop for Menu',
            llmContext: 'asModal prop for Menu - general property for Menu',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'alignment',
            propType: 'MenuAlignment',
            typeDefinition: `MenuAlignment`,
            propDescription: 'alignment prop for Menu',
            llmContext: 'alignment prop for Menu - layout property for Menu',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'side',
            propType: 'MenuSide',
            typeDefinition: `MenuSide`,
            propDescription: 'side prop for Menu',
            llmContext: 'side prop for Menu - general property for Menu',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'sideOffset',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'sideOffset prop for Menu',
            llmContext: 'sideOffset prop for Menu - general property for Menu',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'alignOffset',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'alignOffset prop for Menu',
            llmContext: 'alignOffset prop for Menu - layout property for Menu',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'collisonBoundaryRef',
            propType: 'Element | null | Array<Element | null>',
            typeDefinition: `Element | null | Array<Element | null>`,
            propDescription: 'collisonBoundaryRef prop for Menu',
            llmContext:
                'collisonBoundaryRef prop for Menu - events property for Menu',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
    ],
}

export default menuMeta
