const modalMeta = {
    componentName: 'Modal',
    componentDescription:
        'A dialog component that displays content in a layer above the main application.',
    features: [
        'Overlay backdrop',
        'Focus management',
        'Escape key handling',
        'Customizable sizes',
        'Animation support',
    ],
    usageExamples: [
        {
            title: 'Basic Modal',
            description: 'Simple modal usage',
            code: '<Modal />',
        },
        {
            title: 'Modal with Content',
            description: 'Modal with title and content',
            code: '<Modal isOpen={true} title="Confirm Action">\n  <Text>Are you sure you want to proceed?</Text>\n</Modal>',
        },
    ],
    props: [
        {
            propName: 'isOpen',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'isOpen prop for Modal',
            llmContext: 'isOpen prop for Modal - state property for Modal',
            propDefault: '-',
            category: 'State',
            required: true,
        },
        {
            propName: 'onClose',
            propType: '() => void',
            typeDefinition: `() => void`,
            propDescription: 'onClose prop for Modal',
            llmContext: 'onClose prop for Modal - events property for Modal',
            propDefault: '-',
            category: 'Events',
            required: true,
        },
        {
            propName: 'title',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'title prop for Modal',
            llmContext: 'title prop for Modal - content property for Modal',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'subtitle',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'subtitle prop for Modal',
            llmContext: 'subtitle prop for Modal - content property for Modal',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'children',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'children prop for Modal',
            llmContext: 'children prop for Modal - content property for Modal',
            propDefault: '-',
            category: 'Content',
            required: true,
        },
        {
            propName: 'primaryAction',
            propType: 'ModalButtonAction',
            typeDefinition: `ModalButtonAction`,
            propDescription: 'primaryAction prop for Modal',
            llmContext:
                'primaryAction prop for Modal - events property for Modal',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'secondaryAction',
            propType: 'ModalButtonAction',
            typeDefinition: `ModalButtonAction`,
            propDescription: 'secondaryAction prop for Modal',
            llmContext:
                'secondaryAction prop for Modal - events property for Modal',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'className',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'className prop for Modal',
            llmContext: 'className prop for Modal - styling property for Modal',
            propDefault: 'undefined',
            category: 'Styling',
            required: false,
        },
        {
            propName: 'showCloseButton',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'showCloseButton prop for Modal',
            llmContext:
                'showCloseButton prop for Modal - events property for Modal',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'showHeader',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'showHeader prop for Modal',
            llmContext:
                'showHeader prop for Modal - general property for Modal',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'showFooter',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'showFooter prop for Modal',
            llmContext:
                'showFooter prop for Modal - general property for Modal',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'closeOnBackdropClick',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'closeOnBackdropClick prop for Modal',
            llmContext:
                'closeOnBackdropClick prop for Modal - events property for Modal',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'customHeader',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'customHeader prop for Modal',
            llmContext:
                'customHeader prop for Modal - general property for Modal',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'customFooter',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'customFooter prop for Modal',
            llmContext:
                'customFooter prop for Modal - general property for Modal',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'headerRightSlot',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'headerRightSlot prop for Modal',
            llmContext:
                'headerRightSlot prop for Modal - general property for Modal',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'showDivider',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'showDivider prop for Modal',
            llmContext:
                'showDivider prop for Modal - general property for Modal',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
    ],
}

export default modalMeta
