const multivalueinputMeta = {
    componentName: 'MultiValueInput',
    componentDescription:
        'A multivalueinput component for the Blend design system.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
    ],
    usageExamples: [
        {
            title: 'Basic MultiValueInput',
            description: 'Simple multivalueinput usage',
            code: `<MultiValueInput />`,
        },
    ],
    props: [
        {
            propName: 'label',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'label prop for MultiValueInput',
            llmContext: 'label prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'sublabel',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'sublabel prop for MultiValueInput',
            llmContext: 'sublabel prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'helpIconHintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'helpIconHintText prop for MultiValueInput',
            llmContext: 'helpIconHintText prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'error',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'error prop for MultiValueInput',
            llmContext: 'error prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'errorMessage',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'errorMessage prop for MultiValueInput',
            llmContext: 'errorMessage prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'hintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'hintText prop for MultiValueInput',
            llmContext: 'hintText prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'disabled',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'disabled prop for MultiValueInput',
            llmContext: 'disabled prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'tags',
            propType: 'string[]',
            typeDefinition: `string[]`,
            propDescription: 'tags prop for MultiValueInput',
            llmContext: 'tags prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'onTagAdd',
            propType: '(tag: string) => void',
            typeDefinition: `(tag: string) => void`,
            propDescription: 'onTagAdd prop for MultiValueInput',
            llmContext: 'onTagAdd prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onTagRemove',
            propType: '(tag: string) => void',
            typeDefinition: `(tag: string) => void`,
            propDescription: 'onTagRemove prop for MultiValueInput',
            llmContext: 'onTagRemove prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'size',
            propType: 'TextInputSize',
            typeDefinition: `TextInputSize`,
            propDescription: 'size prop for MultiValueInput',
            llmContext: 'size prop for MultiValueInput',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
    ],
}

export default multivalueinputMeta
