const numberinputMeta = {
    componentName: 'NumberInput',
    componentDescription:
        'A numberinput component for the Blend design system.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
    ],
    usageExamples: [
        {
            title: 'Basic NumberInput',
            description: 'Simple numberinput usage',
            code: `<NumberInput />`,
        },
    ],
    props: [
        {
            propName: 'value',
            propType: 'number | undefined',
            typeDefinition: `number | undefined`,
            propDescription: 'value prop for NumberInput',
            llmContext: 'value prop for NumberInput',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'onChange',
            propType: '(e: React.ChangeEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.ChangeEvent<HTMLInputElement>) => void`,
            propDescription: 'onChange prop for NumberInput',
            llmContext: 'onChange prop for NumberInput',
            propDefault: '-',
            category: 'Events',
            required: true,
        },
        {
            propName: 'step',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'step prop for NumberInput',
            llmContext: 'step prop for NumberInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'error',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'error prop for NumberInput',
            llmContext: 'error prop for NumberInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'errorMessage',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'errorMessage prop for NumberInput',
            llmContext: 'errorMessage prop for NumberInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'size',
            propType: 'NumberInputSize',
            typeDefinition: `enum NumberInputSize {
        MEDIUM = "md",
        LARGE = "lg"
      }`,
            propDescription: 'size prop for NumberInput',
            llmContext: 'size prop for NumberInput',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'label',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'label prop for NumberInput',
            llmContext: 'label prop for NumberInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'sublabel',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'sublabel prop for NumberInput',
            llmContext: 'sublabel prop for NumberInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'helpIconHintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'helpIconHintText prop for NumberInput',
            llmContext: 'helpIconHintText prop for NumberInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'hintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'hintText prop for NumberInput',
            llmContext: 'hintText prop for NumberInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'onBlur',
            propType: '(e: React.FocusEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLInputElement>) => void`,
            propDescription: 'onBlur prop for NumberInput',
            llmContext: 'onBlur prop for NumberInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onFocus',
            propType: '(e: React.FocusEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLInputElement>) => void`,
            propDescription: 'onFocus prop for NumberInput',
            llmContext: 'onFocus prop for NumberInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
    ],
}

export default numberinputMeta
