const popoverMeta = {
    componentName: 'Popover',
    componentDescription:
        'A floating content component that displays additional information or actions.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
        'Part of the Blend design system',
    ],
    usageExamples: [
        {
            title: 'Basic Popover',
            description: 'Simple popover usage',
            code: '<Popover />',
        },
    ],
    props: [
        {
            propName: 'heading',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'heading prop for Popover',
            llmContext:
                'heading prop for Popover - general property for Popover',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'description',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'description prop for Popover',
            llmContext:
                'description prop for Popover - events property for Popover',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'trigger',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'trigger prop for Popover',
            llmContext:
                'trigger prop for Popover - general property for Popover',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'children',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'children prop for Popover',
            llmContext:
                'children prop for Popover - content property for Popover',
            propDefault: '-',
            category: 'Content',
            required: true,
        },
        {
            propName: 'showCloseButton',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'showCloseButton prop for Popover',
            llmContext:
                'showCloseButton prop for Popover - events property for Popover',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onOpenChange',
            propType: '(open: boolean) => void',
            typeDefinition: `(open: boolean) => void`,
            propDescription: 'onOpenChange prop for Popover',
            llmContext:
                'onOpenChange prop for Popover - events property for Popover',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'open',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'open prop for Popover',
            llmContext: 'open prop for Popover - state property for Popover',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'asModal',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'asModal prop for Popover',
            llmContext:
                'asModal prop for Popover - general property for Popover',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'primaryAction',
            propType: 'PopoverActionType',
            typeDefinition: `PopoverActionType`,
            propDescription: 'primaryAction prop for Popover',
            llmContext:
                'primaryAction prop for Popover - events property for Popover',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'secondaryAction',
            propType: 'PopoverActionType',
            typeDefinition: `PopoverActionType`,
            propDescription: 'secondaryAction prop for Popover',
            llmContext:
                'secondaryAction prop for Popover - events property for Popover',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'sideOffset',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'sideOffset prop for Popover',
            llmContext:
                'sideOffset prop for Popover - general property for Popover',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'side',
            propType: "'top' | 'right' | 'bottom' | 'left'",
            typeDefinition: `\'top\' | \'right\' | \'bottom\' | \'left\'`,
            propDescription: 'side prop for Popover',
            llmContext: 'side prop for Popover - general property for Popover',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'align',
            propType: "'start' | 'center' | 'end'",
            typeDefinition: `\'start\' | \'center\' | \'end\'`,
            propDescription: 'align prop for Popover',
            llmContext: 'align prop for Popover - layout property for Popover',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'alignOffset',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'alignOffset prop for Popover',
            llmContext:
                'alignOffset prop for Popover - layout property for Popover',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'width',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'width prop for Popover',
            llmContext: 'width prop for Popover - layout property for Popover',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'minWidth',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'minWidth prop for Popover',
            llmContext:
                'minWidth prop for Popover - layout property for Popover',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'maxWidth',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'maxWidth prop for Popover',
            llmContext:
                'maxWidth prop for Popover - layout property for Popover',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'height',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'height prop for Popover',
            llmContext: 'height prop for Popover - layout property for Popover',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'minHeight',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'minHeight prop for Popover',
            llmContext:
                'minHeight prop for Popover - layout property for Popover',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'maxHeight',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'maxHeight prop for Popover',
            llmContext:
                'maxHeight prop for Popover - layout property for Popover',
            propDefault: 'undefined',
            category: 'Layout',
            required: false,
        },
        {
            propName: 'zIndex',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'zIndex prop for Popover',
            llmContext:
                'zIndex prop for Popover - general property for Popover',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'size',
            propType: 'PopoverSize',
            typeDefinition: `PopoverSize`,
            propDescription: 'size prop for Popover',
            llmContext:
                'size prop for Popover - appearance property for Popover',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'onClose',
            propType: '() => void',
            typeDefinition: `() => void`,
            propDescription: 'onClose prop for Popover',
            llmContext:
                'onClose prop for Popover - events property for Popover',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
    ],
}

export default popoverMeta
