const radioMeta = {
    componentName: 'Radio',
    componentDescription:
        'A form control that allows users to select one option from a set of mutually exclusive choices.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
        'Part of the Blend design system',
    ],
    usageExamples: [
        {
            title: 'Basic Radio',
            description: 'Simple radio usage',
            code: '<Radio />',
        },
    ],
    props: [
        {
            propName: 'id',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'id prop for Radio',
            llmContext: 'id prop for Radio - general property for Radio',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'value',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'value prop for Radio',
            llmContext: 'value prop for Radio - general property for Radio',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'checked',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'checked prop for Radio',
            llmContext: 'checked prop for Radio - general property for Radio',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'defaultChecked',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'defaultChecked prop for Radio',
            llmContext:
                'defaultChecked prop for Radio - general property for Radio',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'onChange',
            propType: '(checked: boolean) => void',
            typeDefinition: `(checked: boolean) => void`,
            propDescription: 'onChange prop for Radio',
            llmContext: 'onChange prop for Radio - events property for Radio',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'disabled',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'disabled prop for Radio',
            llmContext: 'disabled prop for Radio - state property for Radio',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'required',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'required prop for Radio',
            llmContext: 'required prop for Radio - general property for Radio',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'error',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'error prop for Radio',
            llmContext: 'error prop for Radio - general property for Radio',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'size',
            propType: 'RadioSize',
            typeDefinition: `RadioSize`,
            propDescription: 'size prop for Radio',
            llmContext: 'size prop for Radio - appearance property for Radio',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'children',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'children prop for Radio',
            llmContext: 'children prop for Radio - content property for Radio',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'subtext',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'subtext prop for Radio',
            llmContext: 'subtext prop for Radio - content property for Radio',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'slot',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'slot prop for Radio',
            llmContext: 'slot prop for Radio - general property for Radio',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'name',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'name prop for Radio',
            llmContext: 'name prop for Radio - general property for Radio',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
    ],
}

export default radioMeta
