const switchMeta = {
    componentName: 'Switch',
    componentDescription:
        'A toggle component that allows users to switch between two states.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
        'Part of the Blend design system',
    ],
    usageExamples: [
        {
            title: 'Basic Switch',
            description: 'Simple switch usage',
            code: '<Switch />',
        },
    ],
    props: [
        {
            propName: 'id',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'id prop for Switch',
            llmContext: 'id prop for Switch - general property for Switch',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'checked',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'checked prop for Switch',
            llmContext: 'checked prop for Switch - general property for Switch',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'defaultChecked',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'defaultChecked prop for Switch',
            llmContext:
                'defaultChecked prop for Switch - general property for Switch',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'onChange',
            propType: '(checked: boolean) => void',
            typeDefinition: `(checked: boolean) => void`,
            propDescription: 'onChange prop for Switch',
            llmContext: 'onChange prop for Switch - events property for Switch',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'disabled',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'disabled prop for Switch',
            llmContext: 'disabled prop for Switch - state property for Switch',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'required',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'required prop for Switch',
            llmContext:
                'required prop for Switch - general property for Switch',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'error',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'error prop for Switch',
            llmContext: 'error prop for Switch - general property for Switch',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'size',
            propType: 'SwitchSize',
            typeDefinition: `SwitchSize`,
            propDescription: 'size prop for Switch',
            llmContext: 'size prop for Switch - appearance property for Switch',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'label',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'label prop for Switch',
            llmContext: 'label prop for Switch - content property for Switch',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'subtext',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'subtext prop for Switch',
            llmContext: 'subtext prop for Switch - content property for Switch',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'slot',
            propType: 'ReactNode',
            typeDefinition: `ReactNode`,
            propDescription: 'slot prop for Switch',
            llmContext: 'slot prop for Switch - general property for Switch',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'name',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'name prop for Switch',
            llmContext: 'name prop for Switch - general property for Switch',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'value',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'value prop for Switch',
            llmContext: 'value prop for Switch - general property for Switch',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
    ],
}

export default switchMeta
