const textareaMeta = {
    componentName: 'TextArea',
    componentDescription: 'A textarea component for the Blend design system.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
    ],
    usageExamples: [
        {
            title: 'Basic TextArea',
            description: 'Simple textarea usage',
            code: `<TextArea />`,
        },
    ],
    props: [
        {
            propName: 'value',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'value prop for TextArea',
            llmContext: 'value prop for TextArea',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'placeholder',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'placeholder prop for TextArea',
            llmContext: 'placeholder prop for TextArea',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'disabled',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'disabled prop for TextArea',
            llmContext: 'disabled prop for TextArea',
            propDefault: 'undefined',
            category: 'State',
            required: false,
        },
        {
            propName: 'autoFocus',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'autoFocus prop for TextArea',
            llmContext: 'autoFocus prop for TextArea',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'onChange',
            propType: '(e: React.ChangeEvent<HTMLTextAreaElement>) => void',
            typeDefinition: `(e: React.ChangeEvent<HTMLTextAreaElement>) => void`,
            propDescription: 'onChange prop for TextArea',
            llmContext: 'onChange prop for TextArea',
            propDefault: '-',
            category: 'Events',
            required: true,
        },
        {
            propName: 'onFocus',
            propType: '(e: React.FocusEvent<HTMLTextAreaElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLTextAreaElement>) => void`,
            propDescription: 'onFocus prop for TextArea',
            llmContext: 'onFocus prop for TextArea',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onBlur',
            propType: '(e: React.FocusEvent<HTMLTextAreaElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLTextAreaElement>) => void`,
            propDescription: 'onBlur prop for TextArea',
            llmContext: 'onBlur prop for TextArea',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'rows',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'rows prop for TextArea',
            llmContext: 'rows prop for TextArea',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'cols',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'cols prop for TextArea',
            llmContext: 'cols prop for TextArea',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'label',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'label prop for TextArea',
            llmContext: 'label prop for TextArea',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'sublabel',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'sublabel prop for TextArea',
            llmContext: 'sublabel prop for TextArea',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'hintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'hintText prop for TextArea',
            llmContext: 'hintText prop for TextArea',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'helpIconHintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'helpIconHintText prop for TextArea',
            llmContext: 'helpIconHintText prop for TextArea',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'helpIconText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'helpIconText prop for TextArea',
            llmContext: 'helpIconText prop for TextArea',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'required',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'required prop for TextArea',
            llmContext: 'required prop for TextArea',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'error',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'error prop for TextArea',
            llmContext: 'error prop for TextArea',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'errorMessage',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'errorMessage prop for TextArea',
            llmContext: 'errorMessage prop for TextArea',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'resize',
            propType:
                "'none' | 'both' | 'horizontal' | 'vertical' | 'block' | 'inline'",
            typeDefinition: `'none' | 'both' | 'horizontal' | 'vertical' | 'block' | 'inline'`,
            propDescription: 'resize prop for TextArea',
            llmContext: 'resize prop for TextArea',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'wrap',
            propType: "CSSObject['whiteSpace']",
            typeDefinition: `CSSObject['whiteSpace']`,
            propDescription: 'wrap prop for TextArea',
            llmContext: 'wrap prop for TextArea',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
    ],
}

export default textareaMeta
