const textinputMeta = {
    componentName: 'TextInput',
    componentDescription: 'A textinput component for the Blend design system.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
    ],
    usageExamples: [
        {
            title: 'Basic TextInput',
            description: 'Simple textinput usage',
            code: `<TextInput />`,
        },
    ],
    props: [
        {
            propName: 'label',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'label prop for TextInput',
            llmContext: 'label prop for TextInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'sublabel',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'sublabel prop for TextInput',
            llmContext: 'sublabel prop for TextInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'hintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'hintText prop for TextInput',
            llmContext: 'hintText prop for TextInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'helpIconHintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'helpIconHintText prop for TextInput',
            llmContext: 'helpIconHintText prop for TextInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'error',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'error prop for TextInput',
            llmContext: 'error prop for TextInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'errorMessage',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'errorMessage prop for TextInput',
            llmContext: 'errorMessage prop for TextInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'size',
            propType: 'TextInputSize',
            typeDefinition: `enum TextInputSize {
        MEDIUM = "md",
        LARGE = "lg"
      }`,
            propDescription: 'size prop for TextInput',
            llmContext: 'size prop for TextInput',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'leftSlot',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'leftSlot prop for TextInput',
            llmContext: 'leftSlot prop for TextInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'rightSlot',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'rightSlot prop for TextInput',
            llmContext: 'rightSlot prop for TextInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'value',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'value prop for TextInput',
            llmContext: 'value prop for TextInput',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'onChange',
            propType: '(e: React.ChangeEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.ChangeEvent<HTMLInputElement>) => void`,
            propDescription: 'onChange prop for TextInput',
            llmContext: 'onChange prop for TextInput',
            propDefault: '-',
            category: 'Events',
            required: true,
        },
        {
            propName: 'onBlur',
            propType: '(e: React.FocusEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLInputElement>) => void`,
            propDescription: 'onBlur prop for TextInput',
            llmContext: 'onBlur prop for TextInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onFocus',
            propType: '(e: React.FocusEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLInputElement>) => void`,
            propDescription: 'onFocus prop for TextInput',
            llmContext: 'onFocus prop for TextInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
    ],
}

export default textinputMeta
