const unitinputMeta = {
    componentName: 'UnitInput',
    componentDescription: 'A unitinput component for the Blend design system.',
    features: [
        'Customizable appearance and behavior',
        'Accessible design',
        'Responsive layout',
    ],
    usageExamples: [
        {
            title: 'Basic UnitInput',
            description: 'Simple unitinput usage',
            code: `<UnitInput />`,
        },
    ],
    props: [
        {
            propName: 'value',
            propType: 'number | undefined',
            typeDefinition: `number | undefined`,
            propDescription: 'value prop for UnitInput',
            llmContext: 'value prop for UnitInput',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'onChange',
            propType: '(e: React.ChangeEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.ChangeEvent<HTMLInputElement>) => void`,
            propDescription: 'onChange prop for UnitInput',
            llmContext: 'onChange prop for UnitInput',
            propDefault: '-',
            category: 'Events',
            required: true,
        },
        {
            propName: 'step',
            propType: 'number',
            typeDefinition: `number`,
            propDescription: 'step prop for UnitInput',
            llmContext: 'step prop for UnitInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'error',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'error prop for UnitInput',
            llmContext: 'error prop for UnitInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'errorMessage',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'errorMessage prop for UnitInput',
            llmContext: 'errorMessage prop for UnitInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'required',
            propType: 'boolean',
            typeDefinition: `boolean`,
            propDescription: 'required prop for UnitInput',
            llmContext: 'required prop for UnitInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'size',
            propType: 'UnitInputSize',
            typeDefinition: `enum UnitInputSize {
        MEDIUM = "md",
        LARGE = "lg"
      }`,
            propDescription: 'size prop for UnitInput',
            llmContext: 'size prop for UnitInput',
            propDefault: 'undefined',
            category: 'Appearance',
            required: false,
        },
        {
            propName: 'label',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'label prop for UnitInput',
            llmContext: 'label prop for UnitInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'sublabel',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'sublabel prop for UnitInput',
            llmContext: 'sublabel prop for UnitInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'helpIconHintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'helpIconHintText prop for UnitInput',
            llmContext: 'helpIconHintText prop for UnitInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'hintText',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'hintText prop for UnitInput',
            llmContext: 'hintText prop for UnitInput',
            propDefault: 'undefined',
            category: 'Content',
            required: false,
        },
        {
            propName: 'leftSlot',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'leftSlot prop for UnitInput',
            llmContext: 'leftSlot prop for UnitInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'rightSlot',
            propType: 'React.ReactNode',
            typeDefinition: `React.ReactNode`,
            propDescription: 'rightSlot prop for UnitInput',
            llmContext: 'rightSlot prop for UnitInput',
            propDefault: 'undefined',
            category: 'General',
            required: false,
        },
        {
            propName: 'unit',
            propType: 'string',
            typeDefinition: `string`,
            propDescription: 'unit prop for UnitInput',
            llmContext: 'unit prop for UnitInput',
            propDefault: '-',
            category: 'General',
            required: true,
        },
        {
            propName: 'unitPosition',
            propType: 'UnitPosition',
            typeDefinition: `enum UnitPosition {
        LEFT = "left",
        RIGHT = "right"
      }`,
            propDescription: 'unitPosition prop for UnitInput',
            llmContext: 'unitPosition prop for UnitInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onFocus',
            propType: '(e: React.FocusEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLInputElement>) => void`,
            propDescription: 'onFocus prop for UnitInput',
            llmContext: 'onFocus prop for UnitInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
        {
            propName: 'onBlur',
            propType: '(e: React.FocusEvent<HTMLInputElement>) => void',
            typeDefinition: `(e: React.FocusEvent<HTMLInputElement>) => void`,
            propDescription: 'onBlur prop for UnitInput',
            llmContext: 'onBlur prop for UnitInput',
            propDefault: 'undefined',
            category: 'Events',
            required: false,
        },
    ],
}

export default unitinputMeta
