/**
 * Color Scale Generator
 *
 * Generates a full 50–950 color scale from a single hex color.
 * Uses simple HSL-based lightness interpolation for perceptually
 * uniform results.
 *
 * Usage:
 *   generateColorScale("#E31837")
 *   // → { 50: "#FEF2F2", 100: "#FFE2E2", ..., 500: "#E31837", ..., 950: "#400810" }
 */

import type { ColorOverrides } from './types'

// ---------------------------------------------------------------------------
// Hex ↔ HSL conversions
// ---------------------------------------------------------------------------

interface HSL {
    h: number // 0–360
    s: number // 0–100
    l: number // 0–100
}

function hexToRGB(hex: string): { r: number; g: number; b: number } {
    const clean = hex.replace('#', '')
    return {
        r: parseInt(clean.slice(0, 2), 16),
        g: parseInt(clean.slice(2, 4), 16),
        b: parseInt(clean.slice(4, 6), 16),
    }
}

function rgbToHex(r: number, g: number, b: number): string {
    const clamp = (v: number) => Math.round(Math.max(0, Math.min(255, v)))
    const toHex = (v: number) => clamp(v).toString(16).padStart(2, '0')
    return `#${toHex(r)}${toHex(g)}${toHex(b)}`.toUpperCase()
}

function rgbToHSL(r: number, g: number, b: number): HSL {
    const rn = r / 255
    const gn = g / 255
    const bn = b / 255

    const max = Math.max(rn, gn, bn)
    const min = Math.min(rn, gn, bn)
    const delta = max - min

    let h = 0
    let s = 0
    const l = (max + min) / 2

    if (delta !== 0) {
        s = l > 0.5 ? delta / (2 - max - min) : delta / (max + min)

        if (max === rn) h = ((gn - bn) / delta + (gn < bn ? 6 : 0)) * 60
        else if (max === gn) h = ((bn - rn) / delta + 2) * 60
        else h = ((rn - gn) / delta + 4) * 60
    }

    return { h, s: s * 100, l: l * 100 }
}

function hslToRGB(
    h: number,
    s: number,
    l: number
): { r: number; g: number; b: number } {
    const sn = s / 100
    const ln = l / 100

    const c = (1 - Math.abs(2 * ln - 1)) * sn
    const x = c * (1 - Math.abs(((h / 60) % 2) - 1))
    const m = ln - c / 2

    let r = 0
    let g = 0
    let b = 0

    if (h < 60) {
        r = c
        g = x
        b = 0
    } else if (h < 120) {
        r = x
        g = c
        b = 0
    } else if (h < 180) {
        r = 0
        g = c
        b = x
    } else if (h < 240) {
        r = 0
        g = x
        b = c
    } else if (h < 300) {
        r = x
        g = 0
        b = c
    } else {
        r = c
        g = 0
        b = x
    }

    return {
        r: Math.round((r + m) * 255),
        g: Math.round((g + m) * 255),
        b: Math.round((b + m) * 255),
    }
}

// ---------------------------------------------------------------------------
// Scale generation
// ---------------------------------------------------------------------------

/**
 * Target lightness values for each shade in the scale.
 * Shade 500 is the input color — the rest are interpolated.
 */
const SHADE_LIGHTNESS: Record<string, number> = {
    '50': 96,
    '100': 92,
    '200': 84,
    '300': 72,
    '400': 58,
    '500': 0, // placeholder — uses the actual input lightness
    '600': 0, // calculated relative to 500
    '700': 0,
    '800': 0,
    '900': 0,
    '950': 0,
}

/**
 * Generate a full 50–950 color scale from a single hex color.
 *
 * The input color is placed at shade 500. Lighter shades (50–400)
 * are generated by increasing lightness. Darker shades (600–950)
 * are generated by decreasing lightness, with slight saturation boost.
 */
export function generateColorScale(hex: string): ColorOverrides {
    const rgb = hexToRGB(hex)
    const hsl = rgbToHSL(rgb.r, rgb.g, rgb.b)

    const scale: ColorOverrides = {}

    // Light shades: interpolate from near-white to the input color
    const lightShades = ['50', '100', '200', '300', '400']
    for (const shade of lightShades) {
        const targetL = SHADE_LIGHTNESS[shade]!
        // Desaturate lighter shades slightly for a natural feel
        const factor = (targetL - hsl.l) / (96 - hsl.l)
        const adjustedS = hsl.s * (1 - factor * 0.3)
        const { r, g, b } = hslToRGB(hsl.h, Math.max(0, adjustedS), targetL)
        scale[shade] = rgbToHex(r, g, b)
    }

    // 500 = the input color
    scale['500'] = hex.toUpperCase()

    // Dark shades: decrease lightness, slightly increase saturation
    const darkShades: Array<{ shade: string; lDelta: number }> = [
        { shade: '600', lDelta: -8 },
        { shade: '700', lDelta: -18 },
        { shade: '800', lDelta: -26 },
        { shade: '900', lDelta: -34 },
        { shade: '950', lDelta: -42 },
    ]

    for (const { shade, lDelta } of darkShades) {
        const newL = Math.max(5, hsl.l + lDelta)
        const newS = Math.min(100, hsl.s * 1.05) // subtle saturation boost
        const { r, g, b } = hslToRGB(hsl.h, newS, newL)
        scale[shade] = rgbToHex(r, g, b)
    }

    return scale
}

/**
 * Validate that a string is a valid hex color (#RGB or #RRGGBB).
 */
export function isValidHexColor(value: string): boolean {
    return /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/.test(value)
}